
version: 2.1

jobs:
  scan:
    machine:
      image: ubuntu-2004:2022.04.1
    steps:
      - checkout
      - run:
          name: zap_scan
          shell: /bin/bash
          command: |
              docker run --user 0 --rm -v $(pwd):/zap/wrk/:rw -t ictu/zap2docker-weekly zap-full-scan.py -d -I -j \
              -t https://zap.productplan.com \
              -r security_report.html \
              --hook=/zap/auth_hook.py \
              -z "auth.loginurl=https://zap.productplan.com/users/sign_in \
              auth.username=$ZAP_USER \
              auth.password=$ZAP_PASSWORD \
              auth.username_field="user_email" \
              auth.password_field="user_password" \
              auth.submit_field="sign_in" \
              auth.check_delay=15"

      - run:
          name: send_report
          shell: /bin/bash
          command: ./sendreport

      - store_artifacts:
          path: /home/circleci/project/security_report.html
          destination: reports/security_report.html

workflows:
   build_and_test:
    jobs:
      - scan
